import 'package:lang_learn_mobile/core/entities/languages.dart';
import 'package:lang_learn_mobile/core/entities/litera.dart';
import 'package:lang_learn_mobile/features/memory_cards/domain/entities/flashcard.dart';

const List<Flashcard> householdMemoryCards = [
  Flashcard(
    id: '29',
    fWord: Literal(
      id: '29',
      word: 'Дом',
      transcript: 'Dom',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '29',
      word: 'Үй',
      transcript: 'Üy',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '30',
    fWord: Literal(
      id: '30',
      word: 'Еда',
      transcript: 'Eda',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '30',
      word: 'Тамак',
      transcript: 'Tamag',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '31',
    fWord: Literal(
      id: '31',
      word: 'Вода',
      transcript: 'Voda',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '31',
      word: 'Суу',
      transcript: 'Suu',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '32',
    fWord: Literal(
      id: '32',
      word: 'Чай',
      transcript: 'Chay',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '32',
      word: 'Чай',
      transcript: 'Chay',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '33',
    fWord: Literal(
      id: '33',
      word: 'Хлеб',
      transcript: 'Hleb',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '33',
      word: 'Нан',
      transcript: 'Nan',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '34',
    fWord: Literal(
      id: '34',
      word: 'Дверь',
      transcript: 'Dver',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '34',
      word: 'Эшик',
      transcript: 'Eshik',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '35',
    fWord: Literal(
      id: '35',
      word: 'Окно',
      transcript: 'Okno',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '35',
      word: 'Терезе',
      transcript: 'Tereze',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '36',
    fWord: Literal(
      id: '36',
      word: 'Стол',
      transcript: 'Stol',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '36',
      word: 'Дасторкон',
      transcript: 'Dastorkon',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '37',
    fWord: Literal(
      id: '37',
      word: 'Стул',
      transcript: 'Stul',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '37',
      word: 'Отургуч',
      transcript: 'Oturguch',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '38',
    fWord: Literal(
      id: '38',
      word: 'Книга',
      transcript: 'Kniga',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '38',
      word: 'Китеп',
      transcript: 'Kitep',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '39',
    fWord: Literal(
      id: '39',
      word: 'Дорога',
      transcript: 'Doroga',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '39',
      word: 'Жол',
      transcript: 'Jol',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '40',
    fWord: Literal(
      id: '40',
      word: 'Рынок',
      transcript: 'Rynok',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '40',
      word: 'Базар',
      transcript: 'Bazar',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
];
