import 'package:lang_learn_mobile/core/entities/languages.dart';
import 'package:lang_learn_mobile/core/entities/litera.dart';
import 'package:lang_learn_mobile/features/memory_cards/domain/entities/flashcard.dart';

const List<Flashcard> numbersMemoryCards = [
  Flashcard(
    id: '0',
    fWord: Literal(
      id: '0',
      word: 'Ноль',
      transcript: 'Nol',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '0',
      word: 'Нөл',
      transcript: 'Nöl',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '1',
    fWord: Literal(
      id: '1',
      word: 'Один',
      transcript: 'Odin',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '1',
      word: 'Бир',
      transcript: 'Bir',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '2',
    fWord: Literal(
      id: '2',
      word: 'Два',
      transcript: 'Dva',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '2',
      word: 'Эки',
      transcript: 'Eki',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '3',
    fWord: Literal(
      id: '3',
      word: 'Три',
      transcript: 'Tri',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '3',
      word: 'Үч',
      transcript: 'Üch',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '4',
    fWord: Literal(
      id: '4',
      word: 'Четыре',
      transcript: 'Chetyre',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '4',
      word: 'Төрт',
      transcript: 'Tört',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '5',
    fWord: Literal(
      id: '5',
      word: 'Пять',
      transcript: 'Pyat',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '5',
      word: 'Беш',
      transcript: 'Besh',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '6',
    fWord: Literal(
      id: '6',
      word: 'Шесть',
      transcript: 'Shest',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '6',
      word: 'Алты',
      transcript: 'Alty',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '7',
    fWord: Literal(
      id: '7',
      word: 'Семь',
      transcript: 'Sem',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '7',
      word: 'Жети',
      transcript: 'Jeti',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '8',
    fWord: Literal(
      id: '8',
      word: 'Восемь',
      transcript: 'Vosem',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '8',
      word: 'Сегиз',
      transcript: 'Segiz',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '9',
    fWord: Literal(
      id: '9',
      word: 'Девять',
      transcript: 'Devyat',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '9',
      word: 'Тогуз',
      transcript: 'Toguz',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '10',
    fWord: Literal(
      id: '10',
      word: 'Десять',
      transcript: 'Desyat',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '10',
      word: 'Он',
      transcript: 'On',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '20',
    fWord: Literal(
      id: '20',
      word: 'Двадцать',
      transcript: 'Dvadtsat',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '20',
      word: 'Жыйырма',
      transcript: 'Jyyrma',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '30',
    fWord: Literal(
      id: '30',
      word: 'Тридцать',
      transcript: 'Tridtsat',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '30',
      word: 'Отуз',
      transcript: 'Otuz',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '40',
    fWord: Literal(
      id: '40',
      word: 'Сорок',
      transcript: 'Sorok',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '40',
      word: 'Кырк',
      transcript: 'Kyrk',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '50',
    fWord: Literal(
      id: '50',
      word: 'Пятьдесят',
      transcript: 'Pyatdesyat',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '50',
      word: 'Элүү',
      transcript: 'Elüü',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '60',
    fWord: Literal(
      id: '60',
      word: 'Шестьдесят',
      transcript: 'Shestdesyat',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '60',
      word: 'Алтымыш',
      transcript: 'Altymysh',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '70',
    fWord: Literal(
      id: '70',
      word: 'Семьдесят',
      transcript: 'Semdesyat',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '70',
      word: 'Жетимиш',
      transcript: 'Jetimish',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '80',
    fWord: Literal(
      id: '80',
      word: 'Восемьдесят',
      transcript: 'Vosemdesyat',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '80',
      word: 'Сексен',
      transcript: 'Seksen',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '90',
    fWord: Literal(
      id: '90',
      word: 'Девяносто',
      transcript: 'Devyatdesyat',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '90',
      word: 'Токсон',
      transcript: 'Tokson',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '100',
    fWord: Literal(
      id: '100',
      word: 'Сто',
      transcript: 'Sto',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '100',
      word: 'Жүз',
      transcript: 'Jüz',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '1000',
    fWord: Literal(
      id: '1000',
      word: 'Тысяча',
      transcript: 'Tysyacha',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '1000',
      word: 'Миң',
      transcript: 'Miŋ',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '10000',
    fWord: Literal(
      id: '10000',
      word: 'Десять тысяч',
      transcript: 'Desyat tysyach',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '10000',
      word: 'Он миң',
      transcript: 'On miŋ',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
];
