import 'package:lang_learn_mobile/features/memory_cards/domain/entities/memory_card.dart';

const List<MemoryCard> numbersMemoryCards = [
  MemoryCard(
    id: '0',
    fWord: 'Ноль',
    fTranscript: 'Nol',
    fLang: 'Russian',
    sWord: 'Нөл',
    sTranscript: 'Nöl',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '1',
    fWord: 'Один',
    fTranscript: 'Odin',
    fLang: 'Russian',
    sWord: 'Бир',
    sTranscript: 'Bir',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '2',
    fWord: 'Два',
    fTranscript: 'Dva',
    fLang: 'Russian',
    sWord: 'Эки',
    sTranscript: 'Eki',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '3',
    fWord: 'Три',
    fTranscript: 'Tri',
    fLang: 'Russian',
    sWord: 'Үч',
    sTranscript: 'Üch',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '4',
    fWord: 'Четыре',
    fTranscript: 'Chetyre',
    fLang: 'Russian',
    sWord: 'Төрт',
    sTranscript: 'Tört',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '5',
    fWord: 'Пять',
    fTranscript: 'Pyat',
    fLang: 'Russian',
    sWord: 'Беш',
    sTranscript: 'Besh',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '6',
    fWord: 'Шесть',
    fTranscript: 'Shest',
    fLang: 'Russian',
    sWord: 'Алты',
    sTranscript: 'Alty',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '7',
    fWord: 'Семь',
    fTranscript: 'Sem',
    fLang: 'Russian',
    sWord: 'Жети',
    sTranscript: 'Jeti',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '8',
    fWord: 'Восемь',
    fTranscript: 'Vosem',
    fLang: 'Russian',
    sWord: 'Сегиз',
    sTranscript: 'Segiz',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '9',
    fWord: 'Девять',
    fTranscript: 'Devyat',
    fLang: 'Russian',
    sWord: 'Тогуз',
    sTranscript: 'Toguz',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '10',
    fWord: 'Десять',
    fTranscript: 'Desyat',
    fLang: 'Russian',
    sWord: 'Он',
    sTranscript: 'On',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '20',
    fWord: 'Двадцать',
    fTranscript: 'Dvadtsat',
    fLang: 'Russian',
    sWord: 'Жыйырма',
    sTranscript: 'Jyyrma',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '30',
    fWord: 'Тридцать',
    fTranscript: 'Tridtsat',
    fLang: 'Russian',
    sWord: 'Отуз',
    sTranscript: 'Otuz',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '40',
    fWord: 'Сорок',
    fTranscript: 'Sorok',
    fLang: 'Russian',
    sWord: 'Кырк',
    sTranscript: 'Kyrk',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '50',
    fWord: 'Пятьдесят',
    fTranscript: 'Pyatdesyat',
    fLang: 'Russian',
    sWord: 'Элүү',
    sTranscript: 'Elüü',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '60',
    fWord: 'Шестьдесят',
    fTranscript: 'Shestdesyat',
    fLang: 'Russian',
    sWord: 'Алтымыш',
    sTranscript: 'Altymysh',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '70',
    fWord: 'Семьдесят',
    fTranscript: 'Semdesyat',
    fLang: 'Russian',
    sWord: 'Жетимиш',
    sTranscript: 'Jetimish',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '80',
    fWord: 'Восемьдесят',
    fTranscript: 'Vosemdesyat',
    fLang: 'Russian',
    sWord: 'Сексен',
    sTranscript: 'Seksen',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '90',
    fWord: 'Девяносто',
    fTranscript: 'Devyatdesyat',
    fLang: 'Russian',
    sWord: 'Токсон',
    sTranscript: 'Tokson',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '100',
    fWord: 'Сто',
    fTranscript: 'Sto',
    fLang: 'Russian',
    sWord: 'Жүз',
    sTranscript: 'Jüz',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '1000',
    fWord: 'Тысяча',
    fTranscript: 'Tysyacha',
    fLang: 'Russian',
    sWord: 'Миң',
    sTranscript: 'Miŋ',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '10000',
    fWord: 'Десять тысяч',
    fTranscript: 'Desyat tysyach',
    fLang: 'Russian',
    sWord: 'Он миң',
    sTranscript: 'On miŋ',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '18',
    fWord: 'Восемнадцать',
    fTranscript: 'Vosemnadtsat',
    fLang: 'Russian',
    sWord: 'Он сегиз',
    sTranscript: 'On segiz',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '23',
    fWord: 'Двадцать три',
    fTranscript: 'Dvadtsat tri',
    fLang: 'Russian',
    sWord: 'Жыйырма үч',
    sTranscript: 'Jyyrma üch',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '37',
    fWord: 'Тридцать семь',
    fTranscript: 'Tridtsat sem',
    fLang: 'Russian',
    sWord: 'Отуз жети',
    sTranscript: 'Otuz jeti',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '45',
    fWord: 'Сорок пять',
    fTranscript: 'Sorok pyat',
    fLang: 'Russian',
    sWord: 'Кырк беш',
    sTranscript: 'Kyrk besh',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '51',
    fWord: 'Пятьдесят один',
    fTranscript: 'Pyatdesyat odin',
    fLang: 'Russian',
    sWord: 'Элүү бир',
    sTranscript: 'Elüü bir',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '66',
    fWord: 'Шестьдесят шесть',
    fTranscript: 'Shestdesyat shest',
    fLang: 'Russian',
    sWord: 'Алтымыш алты',
    sTranscript: 'Altymysh alty',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '78',
    fWord: 'Семьдесят восемь',
    fTranscript: 'Semdesyat vosem',
    fLang: 'Russian',
    sWord: 'Жетимиш сегиз',
    sTranscript: 'Jetimish segiz',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '89',
    fWord: 'Девяносто восемь',
    fTranscript: 'Devyatdesyat vosem',
    fLang: 'Russian',
    sWord: 'Токсон сегиз',
    sTranscript: 'Tokson segiz',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '94',
    fWord: 'Девяносто четыре',
    fTranscript: 'Devyatdesyat chetyre',
    fLang: 'Russian',
    sWord: 'Токсон төрт',
    sTranscript: 'Tokson tört',
    sLang: 'Kyrgyz',
  ),
  MemoryCard(
    id: '101',
    fWord: 'Сто один',
    fTranscript: 'Sto odin',
    fLang: 'Russian',
    sWord: 'Жүз бир',
    sTranscript: 'Jüz bir',
    sLang: 'Kyrgyz',
  ),
];
