import 'package:lang_learn_mobile/core/entities/languages.dart';
import 'package:lang_learn_mobile/core/entities/litera.dart';
import 'package:lang_learn_mobile/features/memory_cards/domain/entities/flashcard.dart';

const List<Flashcard> questionsMemoryCards = [
  Flashcard(
    id: '51',
    fWord: Literal(
      id: '51',
      word: 'Где',
      transcript: 'Gde',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '51',
      word: 'Кайда',
      transcript: 'Kayda',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '52',
    fWord: Literal(
      id: '52',
      word: 'Когда',
      transcript: 'Kogda',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '52',
      word: 'Качан',
      transcript: 'Kachan',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '53',
    fWord: Literal(
      id: '53',
      word: 'Сколько',
      transcript: 'Skolko',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '53',
      word: 'Канча',
      transcript: 'Kancha',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '54',
    fWord: Literal(
      id: '54',
      word: 'Какой/какая',
      transcript: 'Kakoy/kakaya',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '54',
      word: 'Кандай',
      transcript: 'Kanday',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '55',
    fWord: Literal(
      id: '55',
      word: 'Почему',
      transcript: 'Pochemu',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '55',
      word: 'Эмнеге',
      transcript: 'Emnege',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '56',
    fWord: Literal(
      id: '56',
      word: 'Который',
      transcript: 'Kotoriy',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '56',
      word: 'Кайсы',
      transcript: 'Kaysy',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '57',
    fWord: Literal(
      id: '57',
      word: 'Это',
      transcript: 'Eto',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '57',
      word: 'Бул',
      transcript: 'Bul',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '58',
    fWord: Literal(
      id: '58',
      word: 'Тот/та',
      transcript: 'Tot/ta',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '58',
      word: 'Тиги',
      transcript: 'Tigi',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '59',
    fWord: Literal(
      id: '59',
      word: 'Нет',
      transcript: 'Net',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '59',
      word: 'Жок',
      transcript: 'Jok',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '60',
    fWord: Literal(
      id: '60',
      word: 'Да',
      transcript: 'Da',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '60',
      word: 'Ооба',
      transcript: 'Ooba',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
];
