import 'package:lang_learn_mobile/core/entities/languages.dart';
import 'package:lang_learn_mobile/core/entities/litera.dart';
import 'package:lang_learn_mobile/features/memory_cards/domain/entities/flashcard.dart';

const List<Flashcard> verbsMemoryCards = [
  Flashcard(
    id: '41',
    fWord: Literal(
      id: '41',
      word: 'Идти/ехать',
      transcript: 'Idti/ekhat',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '41',
      word: 'Баруу',
      transcript: 'Baruu',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '42',
    fWord: Literal(
      id: '42',
      word: 'Приходить',
      transcript: 'Prikhodit',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '42',
      word: 'Келүү',
      transcript: 'Kelüü',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '43',
    fWord: Literal(
      id: '43',
      word: 'Есть (кушать)',
      transcript: 'Est (kushat)',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '43',
      word: 'Жеүү',
      transcript: 'Jeüü',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '44',
    fWord: Literal(
      id: '44',
      word: 'Пить',
      transcript: 'Pit',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '44',
      word: 'Ичүү',
      transcript: 'Ichüü',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '45',
    fWord: Literal(
      id: '45',
      word: 'Говорить',
      transcript: 'Govorit',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '45',
      word: 'Сүйлөө',
      transcript: 'Süylöö',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '46',
    fWord: Literal(
      id: '46',
      word: 'Видеть',
      transcript: 'Videts',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '46',
      word: 'Көрүү',
      transcript: 'Körüü',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '47',
    fWord: Literal(
      id: '47',
      word: 'Слушать',
      transcript: 'Slushat',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '47',
      word: 'Угуу',
      transcript: 'Uguu',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '48',
    fWord: Literal(
      id: '48',
      word: 'Писать',
      transcript: 'Pisats',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '48',
      word: 'Жазуу',
      transcript: 'Jazuu',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '49',
    fWord: Literal(
      id: '49',
      word: 'Читать',
      transcript: 'Chitat',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '49',
      word: 'Окуу',
      transcript: 'Okuu',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
  Flashcard(
    id: '50',
    fWord: Literal(
      id: '50',
      word: 'Знать',
      transcript: 'Znats',
      lang: Languages.ru,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    sWord: Literal(
      id: '50',
      word: 'Билүү',
      transcript: 'Bilüü',
      lang: Languages.ky,
      hasAudio: false,
      stringHint: '',
      imagePath: '',
    ),
    stringHint: '',
    imagePath: '',
  ),
];
